-- PostgreSQL schema for Mix Loans (Supabase-compatible)
-- Source of truth: live MySQL schema introspection (2026-04-23)

BEGIN;

DO $$
BEGIN
  CREATE TYPE admin_user_role AS ENUM ('super_admin', 'admin', 'staff');
EXCEPTION WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
  CREATE TYPE client_gender AS ENUM ('male', 'female', 'other');
EXCEPTION WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
  CREATE TYPE client_risk_level AS ENUM ('low', 'medium', 'high');
EXCEPTION WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
  CREATE TYPE collateral_status AS ENUM ('held', 'released', 'auctioned', 'returned', 'damaged');
EXCEPTION WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
  CREATE TYPE loan_interest_type AS ENUM ('flat', 'reducing_balance');
EXCEPTION WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
  CREATE TYPE loan_repayment_frequency AS ENUM ('daily', 'weekly', 'biweekly', 'monthly', 'custom');
EXCEPTION WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
  CREATE TYPE loan_duration_unit AS ENUM ('days', 'weeks', 'months');
EXCEPTION WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
  CREATE TYPE loan_status AS ENUM ('draft', 'pending', 'active', 'overdue', 'completed', 'defaulted', 'cancelled');
EXCEPTION WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
  CREATE TYPE loan_schedule_status AS ENUM ('pending', 'partial', 'paid', 'overdue', 'waived');
EXCEPTION WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
  CREATE TYPE payment_method_type AS ENUM ('cash', 'bank_transfer', 'mobile_money', 'card', 'other');
EXCEPTION WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
  CREATE TYPE notification_type AS ENUM ('due_soon', 'overdue', 'payment_received', 'loan_created', 'loan_completed', 'system');
EXCEPTION WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
  CREATE TYPE notification_severity AS ENUM ('info', 'warning', 'critical', 'success');
EXCEPTION WHEN duplicate_object THEN NULL;
END
$$;

DO $$
BEGIN
  CREATE TYPE settings_theme AS ENUM ('light', 'dark', 'system');
EXCEPTION WHEN duplicate_object THEN NULL;
END
$$;

CREATE TABLE IF NOT EXISTS admin_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR(150) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role admin_user_role NOT NULL DEFAULT 'admin',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  last_login_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_user_id BIGINT NULL,
  action_type VARCHAR(100) NOT NULL,
  entity_type VARCHAR(100) NOT NULL,
  entity_id BIGINT NULL,
  description TEXT NOT NULL,
  old_values JSONB NULL,
  new_values JSONB NULL,
  ip_address VARCHAR(64) NULL,
  user_agent VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_audit_logs_admin_user FOREIGN KEY (admin_user_id)
    REFERENCES admin_users(id)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_code VARCHAR(50) NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  other_names VARCHAR(100) NULL,
  phone VARCHAR(30) NOT NULL,
  email VARCHAR(150) NULL,
  nrc VARCHAR(50) NULL,
  date_of_birth DATE NULL,
  gender client_gender NULL,
  address_line_1 VARCHAR(255) NULL,
  address_line_2 VARCHAR(255) NULL,
  city VARCHAR(100) NULL,
  province VARCHAR(100) NULL,
  country VARCHAR(100) NOT NULL DEFAULT 'Zambia',
  occupation VARCHAR(150) NULL,
  employer_name VARCHAR(150) NULL,
  monthly_income NUMERIC(15, 2) NULL,
  risk_level client_risk_level NOT NULL DEFAULT 'medium',
  notes TEXT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_clients_client_code UNIQUE (client_code),
  CONSTRAINT uq_clients_phone UNIQUE (phone)
);

CREATE TABLE IF NOT EXISTS settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  app_name VARCHAR(100) NOT NULL DEFAULT 'Mix Loans',
  theme settings_theme NOT NULL DEFAULT 'light',
  language VARCHAR(20) NOT NULL DEFAULT 'en',
  currency_code VARCHAR(10) NOT NULL DEFAULT 'ZMW',
  currency_symbol VARCHAR(10) NOT NULL DEFAULT 'K',
  items_per_page INTEGER NOT NULL DEFAULT 10,
  notifications_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  due_soon_days INTEGER NOT NULL DEFAULT 7,
  default_interest_type loan_interest_type NOT NULL DEFAULT 'flat',
  default_interest_rate NUMERIC(7, 4) NOT NULL DEFAULT 0.0000,
  default_grace_period_days INTEGER NOT NULL DEFAULT 0,
  hide_sensitive_info BOOLEAN NOT NULL DEFAULT FALSE,
  dashboard_layout VARCHAR(50) NOT NULL DEFAULT 'default',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_settings_items_per_page CHECK (items_per_page > 0),
  CONSTRAINT chk_settings_due_soon_days CHECK (due_soon_days >= 0),
  CONSTRAINT chk_settings_default_interest_rate CHECK (default_interest_rate >= 0),
  CONSTRAINT chk_settings_default_grace_period_days CHECK (default_grace_period_days >= 0)
);

CREATE TABLE IF NOT EXISTS loans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loan_code VARCHAR(50) NOT NULL,
  client_id BIGINT NOT NULL,
  principal_amount NUMERIC(15, 2) NOT NULL,
  interest_rate NUMERIC(7, 4) NOT NULL,
  interest_type loan_interest_type NOT NULL DEFAULT 'flat',
  repayment_frequency loan_repayment_frequency NOT NULL DEFAULT 'monthly',
  duration_value INTEGER NOT NULL,
  duration_unit loan_duration_unit NOT NULL DEFAULT 'months',
  number_of_installments INTEGER NOT NULL DEFAULT 1,
  start_date DATE NOT NULL,
  first_due_date DATE NULL,
  maturity_date DATE NOT NULL,
  grace_period_days INTEGER NOT NULL DEFAULT 0,
  total_interest NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
  total_penalties NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
  total_repayable NUMERIC(15, 2) NOT NULL,
  amount_paid NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
  remaining_balance NUMERIC(15, 2) NOT NULL,
  status loan_status NOT NULL DEFAULT 'active',
  disbursed_by BIGINT NULL,
  approved_by BIGINT NULL,
  notes TEXT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_loans_loan_code UNIQUE (loan_code),
  CONSTRAINT fk_loans_client FOREIGN KEY (client_id)
    REFERENCES clients(id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT fk_loans_disbursed_by FOREIGN KEY (disbursed_by)
    REFERENCES admin_users(id)
    ON UPDATE CASCADE
    ON DELETE SET NULL,
  CONSTRAINT fk_loans_approved_by FOREIGN KEY (approved_by)
    REFERENCES admin_users(id)
    ON UPDATE CASCADE
    ON DELETE SET NULL,
  CONSTRAINT chk_loans_principal_amount CHECK (principal_amount > 0),
  CONSTRAINT chk_loans_interest_rate CHECK (interest_rate >= 0),
  CONSTRAINT chk_loans_duration_value CHECK (duration_value > 0),
  CONSTRAINT chk_loans_number_of_installments CHECK (number_of_installments > 0),
  CONSTRAINT chk_loans_total_repayable CHECK (total_repayable >= 0),
  CONSTRAINT chk_loans_amount_paid CHECK (amount_paid >= 0),
  CONSTRAINT chk_loans_remaining_balance CHECK (remaining_balance >= 0)
);

CREATE TABLE IF NOT EXISTS collateral (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loan_id BIGINT NOT NULL,
  client_id BIGINT NOT NULL,
  item_type VARCHAR(100) NOT NULL,
  description TEXT NOT NULL,
  serial_number VARCHAR(100) NULL,
  estimated_value NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
  valuation_date DATE NULL,
  status collateral_status NOT NULL DEFAULT 'held',
  storage_location VARCHAR(150) NULL,
  notes TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_collateral_loan FOREIGN KEY (loan_id)
    REFERENCES loans(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT fk_collateral_client FOREIGN KEY (client_id)
    REFERENCES clients(id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT chk_collateral_estimated_value CHECK (estimated_value >= 0)
);

CREATE TABLE IF NOT EXISTS loan_schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loan_id BIGINT NOT NULL,
  installment_number INTEGER NOT NULL,
  due_date DATE NOT NULL,
  principal_due NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
  interest_due NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
  penalty_due NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
  total_due NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
  amount_paid NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
  remaining_due NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
  status loan_schedule_status NOT NULL DEFAULT 'pending',
  paid_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_loan_schedules_loan_installment UNIQUE (loan_id, installment_number),
  CONSTRAINT fk_loan_schedules_loan FOREIGN KEY (loan_id)
    REFERENCES loans(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT chk_loan_schedules_installment_number CHECK (installment_number > 0),
  CONSTRAINT chk_loan_schedules_total_due CHECK (total_due >= 0),
  CONSTRAINT chk_loan_schedules_amount_paid CHECK (amount_paid >= 0),
  CONSTRAINT chk_loan_schedules_remaining_due CHECK (remaining_due >= 0)
);

CREATE TABLE IF NOT EXISTS payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_code VARCHAR(50) NOT NULL,
  loan_id BIGINT NOT NULL,
  schedule_id BIGINT NULL,
  payment_date TIMESTAMP NOT NULL,
  amount NUMERIC(15, 2) NOT NULL,
  principal_applied NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
  interest_applied NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
  penalty_applied NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
  payment_method payment_method_type NOT NULL DEFAULT 'cash',
  reference_number VARCHAR(100) NULL,
  received_by BIGINT NULL,
  notes TEXT NULL,
  is_reversed BOOLEAN NOT NULL DEFAULT FALSE,
  reversed_at TIMESTAMP NULL,
  reversal_reason VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_payments_payment_code UNIQUE (payment_code),
  CONSTRAINT fk_payments_loan FOREIGN KEY (loan_id)
    REFERENCES loans(id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  CONSTRAINT fk_payments_schedule FOREIGN KEY (schedule_id)
    REFERENCES loan_schedules(id)
    ON UPDATE CASCADE
    ON DELETE SET NULL,
  CONSTRAINT fk_payments_received_by FOREIGN KEY (received_by)
    REFERENCES admin_users(id)
    ON UPDATE CASCADE
    ON DELETE SET NULL,
  CONSTRAINT chk_payments_amount CHECK (amount > 0),
  CONSTRAINT chk_payments_principal_applied CHECK (principal_applied >= 0),
  CONSTRAINT chk_payments_interest_applied CHECK (interest_applied >= 0),
  CONSTRAINT chk_payments_penalty_applied CHECK (penalty_applied >= 0)
);

CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  related_loan_id BIGINT NULL,
  related_client_id BIGINT NULL,
  type notification_type NOT NULL,
  title VARCHAR(150) NOT NULL,
  message TEXT NOT NULL,
  severity notification_severity NOT NULL DEFAULT 'info',
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  read_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_notifications_loan FOREIGN KEY (related_loan_id)
    REFERENCES loans(id)
    ON UPDATE CASCADE
    ON DELETE SET NULL,
  CONSTRAINT fk_notifications_client FOREIGN KEY (related_client_id)
    REFERENCES clients(id)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  expense_code VARCHAR(50) NOT NULL,
  expense_date DATE NOT NULL,
  category VARCHAR(100) NOT NULL,
  amount NUMERIC(15, 2) NOT NULL,
  description TEXT NULL,
  recorded_by BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_expenses_expense_code UNIQUE (expense_code),
  CONSTRAINT fk_expenses_recorded_by FOREIGN KEY (recorded_by)
    REFERENCES admin_users(id)
    ON UPDATE CASCADE
    ON DELETE SET NULL,
  CONSTRAINT chk_expenses_amount CHECK (amount > 0)
);

CREATE TABLE IF NOT EXISTS guarantors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT NOT NULL,
  full_name VARCHAR(150) NOT NULL,
  phone VARCHAR(30) NOT NULL,
  nrc VARCHAR(50) NULL,
  address VARCHAR(255) NULL,
  relationship_to_client VARCHAR(100) NULL,
  notes TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_guarantors_client FOREIGN KEY (client_id)
    REFERENCES clients(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_admin_user_id ON audit_logs(admin_user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action_type ON audit_logs(action_type);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON audit_logs(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(created_at);

CREATE INDEX IF NOT EXISTS idx_clients_name ON clients(first_name, last_name);
CREATE INDEX IF NOT EXISTS idx_clients_risk_level ON clients(risk_level);

CREATE INDEX IF NOT EXISTS idx_loans_client_id ON loans(client_id);
CREATE INDEX IF NOT EXISTS idx_loans_status ON loans(status);
CREATE INDEX IF NOT EXISTS idx_loans_maturity_date ON loans(maturity_date);
CREATE INDEX IF NOT EXISTS idx_loans_disbursed_by ON loans(disbursed_by);
CREATE INDEX IF NOT EXISTS idx_loans_approved_by ON loans(approved_by);

CREATE INDEX IF NOT EXISTS idx_collateral_loan_id ON collateral(loan_id);
CREATE INDEX IF NOT EXISTS idx_collateral_client_id ON collateral(client_id);
CREATE INDEX IF NOT EXISTS idx_collateral_status ON collateral(status);

CREATE INDEX IF NOT EXISTS idx_loan_schedules_due_date ON loan_schedules(due_date);
CREATE INDEX IF NOT EXISTS idx_loan_schedules_status ON loan_schedules(status);

CREATE INDEX IF NOT EXISTS idx_payments_loan_id ON payments(loan_id);
CREATE INDEX IF NOT EXISTS idx_payments_schedule_id ON payments(schedule_id);
CREATE INDEX IF NOT EXISTS idx_payments_payment_date ON payments(payment_date);
CREATE INDEX IF NOT EXISTS idx_payments_received_by ON payments(received_by);

CREATE INDEX IF NOT EXISTS idx_notifications_type ON notifications(type);
CREATE INDEX IF NOT EXISTS idx_notifications_is_read ON notifications(is_read);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON notifications(created_at);
CREATE INDEX IF NOT EXISTS idx_notifications_loan ON notifications(related_loan_id);
CREATE INDEX IF NOT EXISTS idx_notifications_client ON notifications(related_client_id);

CREATE INDEX IF NOT EXISTS idx_expenses_expense_date ON expenses(expense_date);
CREATE INDEX IF NOT EXISTS idx_expenses_category ON expenses(category);
CREATE INDEX IF NOT EXISTS idx_expenses_recorded_by ON expenses(recorded_by);

CREATE OR REPLACE FUNCTION set_updated_at_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_admin_users_updated_at ON admin_users;
CREATE TRIGGER trg_admin_users_updated_at
BEFORE UPDATE ON admin_users
FOR EACH ROW
EXECUTE FUNCTION set_updated_at_timestamp();

DROP TRIGGER IF EXISTS trg_clients_updated_at ON clients;
CREATE TRIGGER trg_clients_updated_at
BEFORE UPDATE ON clients
FOR EACH ROW
EXECUTE FUNCTION set_updated_at_timestamp();

DROP TRIGGER IF EXISTS trg_settings_updated_at ON settings;
CREATE TRIGGER trg_settings_updated_at
BEFORE UPDATE ON settings
FOR EACH ROW
EXECUTE FUNCTION set_updated_at_timestamp();

DROP TRIGGER IF EXISTS trg_loans_updated_at ON loans;
CREATE TRIGGER trg_loans_updated_at
BEFORE UPDATE ON loans
FOR EACH ROW
EXECUTE FUNCTION set_updated_at_timestamp();

DROP TRIGGER IF EXISTS trg_collateral_updated_at ON collateral;
CREATE TRIGGER trg_collateral_updated_at
BEFORE UPDATE ON collateral
FOR EACH ROW
EXECUTE FUNCTION set_updated_at_timestamp();

DROP TRIGGER IF EXISTS trg_loan_schedules_updated_at ON loan_schedules;
CREATE TRIGGER trg_loan_schedules_updated_at
BEFORE UPDATE ON loan_schedules
FOR EACH ROW
EXECUTE FUNCTION set_updated_at_timestamp();

DROP TRIGGER IF EXISTS trg_payments_updated_at ON payments;
CREATE TRIGGER trg_payments_updated_at
BEFORE UPDATE ON payments
FOR EACH ROW
EXECUTE FUNCTION set_updated_at_timestamp();

DROP TRIGGER IF EXISTS trg_expenses_updated_at ON expenses;
CREATE TRIGGER trg_expenses_updated_at
BEFORE UPDATE ON expenses
FOR EACH ROW
EXECUTE FUNCTION set_updated_at_timestamp();

DROP TRIGGER IF EXISTS trg_guarantors_updated_at ON guarantors;
CREATE TRIGGER trg_guarantors_updated_at
BEFORE UPDATE ON guarantors
FOR EACH ROW
EXECUTE FUNCTION set_updated_at_timestamp();

COMMIT;
